Repository Luzilla/dnsbl_exporter, pull requests merged in 2024-03, with the labels that each got.

#197 Feat: use scratch base for docker image
  Dockerfile
  README.md
Labels: size/S

#202 Chore(ci): update freebsd image on cirrus
  .cirrus.yml
Labels: size/S

#203 system resolver
  .github/workflows/integration.yml
  README.md
  app/app.go
  internal/resolvconf/fixtures/no-server.conf
  internal/resolvconf/fixtures/two-servers.conf
  internal/resolvconf/resolvconf.go
  internal/resolvconf/resolvconf_test.go
Labels: size/L

#205 Update(unbound): add a small image + workflow to verify
  .docker/unbound/README.md
  .docker/unbound/rootfs/.dockerignore
  .docker/unbound/rootfs/Dockerfile
  .docker/unbound/rootfs/etc/unbound/unbound.conf
  .github/workflows/pr.yml
Labels: size/L

#206 helm chart
  .github/workflows/goreleaser.yml
  .github/workflows/pr.yml
Labels: size/M

#207 Fix(unbound): add missing docker login
  .github/workflows/goreleaser.yml
Labels: size/XS

#208 helm chart
  .docker/unbound/rootfs/Dockerfile
  .docker/unbound/rootfs/etc/unbound/forward-zone.conf
  .docker/unbound/rootfs/etc/unbound/server.conf
  .docker/unbound/rootfs/etc/unbound/unbound.conf
  Makefile
Labels: size/L

#210 Fix(unbound): uid = 100
  .docker/unbound/rootfs/Dockerfile
Labels: size/XS
